---- Database Restoration and Backup Progress ----
SELECT SESSION_ID AS SPID
	,COMMAND
	,A.TEXT AS QUERY
	,START_TIME
	,PERCENT_COMPLETE
	,DATEADD(SECOND, ESTIMATED_COMPLETION_TIME / 1000, GETDATE()) AS ESTIMATED_COMPLETION_TIME
FROM SYS.DM_EXEC_REQUESTS R
CROSS APPLY SYS.DM_EXEC_SQL_TEXT(R.SQL_HANDLE) A
WHERE R.COMMAND IN (
		'BACKUP DATABASE'
		,'RESTORE DATABASE'
		)
